# Generated by Django 5.0.6 on 2024-06-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sliders/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книжки'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='books_choices',
        ),
    ]
